fix decoding of acl's
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/univention/management/console/base.py", line 358, in __error_handling
    six.reraise(etype, exc, etraceback)
  File "/usr/lib/python3/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/univention/management/console/base.py", line 261, in execute
    function.__func__(self, request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/session.py", line 967, in _authentication_finished2
    self.initalize_processor(request)
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/session.py", line 1009, in initalize_processor
    self.processor.set_credentials(**self.__credentials)
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/session.py", line 173, in set_credentials
    self._reload_acls_and_permitted_commands()
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/session.py", line 177, in _reload_acls_and_permitted_commands
    self._reload_acls()
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/session.py", line 182, in _reload_acls
    self.acls = LDAP_ACLs(self.lo, self._username, ucr['ldap/base'])
  File "/usr/lib/python3/dist-packages/univention/management/console/acl.py", line 357, in __init__
    self._read_from_ldap()
  File "/usr/lib/python3/dist-packages/univention/management/console/acl.py", line 394, in _read_from_ldap
    self._append(LDAP_ACLs.FROM_GROUP, self.lo.get(value))
  File "/usr/lib/python3/dist-packages/univention/management/console/acl.py", line 189, in _append
    command, options = self.__parse_command(command)
  File "/usr/lib/python3/dist-packages/univention/management/console/acl.py", line 172, in __parse_command
    if ':' in command:
TypeError: a bytes-like object is required, not 'str'