fix missing __bool__
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/univention/management/console/base.py", line 358, in __error_handling
    six.reraise(etype, exc, etraceback)
  File "/usr/lib/python3/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/univention/management/console/base.py", line 261, in execute
    function.__func__(self, request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/session.py", line 966, in _authentication_finished2
    self.initalize_processor(request)
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/session.py", line 1008, in initalize_processor
    self.processor.set_credentials(**self.__credentials)
TypeError: set_credentials() argument after ** must be a mapping, not NoneType