fix using bytes
Traceback (most recent call last):
  File "/usr/sbin/univention-management-console-server", line 244, in <module>
    umc_daemon.do_action()
  File "/usr/lib/python3/dist-packages/daemon/runner.py", line 267, in do_action
    func(self)
  File "/usr/lib/python3/dist-packages/daemon/runner.py", line 186, in _start
    self.app.run()
  File "/usr/sbin/univention-management-console-server", line 211, in run
    notifier.loop()
  File "/usr/lib/python3/dist-packages/notifier/nf_generic.py", line 296, in loop
    step()
  File "/usr/lib/python3/dist-packages/notifier/nf_generic.py", line 251, in step
    if not timer[CALLBACK]():
  File "/usr/lib/python3/dist-packages/notifier/__init__.py", line 104, in __call__
    return self._function(*tmp, **self._kwargs)
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/session.py", line 578, in _mod_connect
    mod.request(req)
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/client.py", line 279, in request
    if self._resend(sock):
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/client.py", line 199, in _resend
    bytessent = sock.send(data)
TypeError: a bytes-like object is required, not 'str'