PAM exceptions
File "/usr/lib/python3/dist-packages/notifier/threads.py", line 80, in _run
    result = self._function()
  File "/usr/lib/python3/dist-packages/notifier/__init__.py", line 104, in __call__
    return self._function(*tmp, **self._kwargs)
  File "/usr/lib/python3/dist-packages/univention/management/console/auth.py", line 109, in __authenticate_thread
    self.pam.authenticate(username, password, **custom_prompts)
  File "/usr/lib/python3/dist-packages/univention/management/console/pam.py", line 226, in authenticate
    if pam_err[1] == PAM_NEW_AUTHTOK_REQD:  # error: ('Authentication token is no longer valid; new one required', 12)
TypeError: 'error' object does not support indexing