Fix upload
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/univention/management/console/base.py", line 358, in __error_handling
    six.reraise(etype, exc, etraceback)
  File "/usr/lib/python3/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/univention/management/console/base.py", line 261, in execute
    function.__func__(self, request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/decorators.py", line 181, in _response
    return function(self, request)
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/session.py", line 435, in handle_request_upload
    b64buf = base64.b64encode(buf.read())
  File "/usr/lib/python3.5/base64.py", line 59, in b64encode
    encoded = binascii.b2a_base64(s)[:-1]
TypeError: a bytes-like object is required, not 'str'

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/server.py", line 202, in _response
    data = bytes(msg)
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/message.py", line 331, in __bytes__
    return Message._formattedMessage(self._id, self._type, self.mimetype, self.command, body, self.arguments)
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/message.py", line 122, in _formattedMessage
    data = json.dumps(body)
  File "/usr/lib/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: b'S2V2aW4gTG9vcyA8a2V2aW5AdHppLm9yZz4gKHRoZSBmaXJzdCB2ZXJzaW9uIG9mIHRoZSBzb3VyY2Ugd2FzCgkJCSAgIGV4dHJhY3RlZCBmcm9tIHB5TWJ1cyB3aGljaCB3YXMgbWFpbnRhaW5lZAoJCQkgICBieSBLZXZpbiBhdCB0aGlzIHRpbWUpCkFuZHJlYXMgQsO8c2NoaW5nIDxjcnVuY2h5QGJpdGtpcHBlci5uZXQ+IChtYWludGFpbmVyKQo=' is not JSON serializable